{
  "version": 1,
  "status": "fail",
  "message": "[xUnit.net 00:00:00.11]     PartialFail.LeapTests.Year_divisible_by_4_and_5_is_still_a_leap_year [FAIL]\n[xUnit.net 00:00:00.11]     PartialFail.LeapTests.Year_divisible_by_4_not_divisible_by_100_in_leap_year [FAIL]\n  Failed PartialFail.LeapTests.Year_divisible_by_4_and_5_is_still_a_leap_year [1 ms]\n  Error Message:\n   Assert.True() Failure\nExpected: True\nActual:   False\n  Stack Trace:\n     at PartialFail.LeapTests.Year_divisible_by_4_and_5_is_still_a_leap_year() in /solution/PartialFailTests.vb:line 21\n   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)\n   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)\n  Failed PartialFail.LeapTests.Year_divisible_by_4_not_divisible_by_100_in_leap_year [< 1 ms]\n  Error Message:\n   Assert.True() Failure\nExpected: True\nActual:   False\n  Stack Trace:\n     at PartialFail.LeapTests.Year_divisible_by_4_not_divisible_by_100_in_leap_year() in /solution/PartialFailTests.vb:line 16\n   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)\n   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)\n\nFailed!  - Failed:     2, Passed:     7, Skipped:     0, Total:     9,  - PartialFail.dll (net9.0)"
}
